# Generated by Django 3.2.25 on 2024-10-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_app', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_types', to='paper_app.papertype')),
            ],
        ),
    ]
