# Generated by Django 3.2.25 on 2024-10-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_app', '0003_charttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='type',
        ),
        migrations.AddField(
            model_name='entry',
            name='chart_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='paper_app.charttype'),
            preserve_default=False,
        ),
    ]
