# Generated by Django 3.2.25 on 2024-10-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_app', '0005_entry_color_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='examples/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paper_app.entry')),
            ],
        ),
    ]
